extends Node


var crafting = {
   "cloth_helmet":{
	  "secs_to_craft":"668",
	  "gold_to_craft":"68",
	  "xp_from_craft":"1124",
	  "crafted_in_bench":true,
	  "materials":{
		 "cloth":"3"
	  }
   },
   "cloth_chestplate":{
	  "secs_to_craft":"703",
	  "gold_to_craft":"104",
	  "xp_from_craft":"1512",
	  "crafted_in_bench":true,
	  "materials":{
		 "cloth":"4"
	  }
   },
   "cloth_gloves":{
	  "secs_to_craft":"634",
	  "gold_to_craft":"40",
	  "xp_from_craft":"760",
	  "crafted_in_bench":true,
	  "materials":{
		 "cloth":"2"
	  }
   },
   "cloth_boots":{
	  "secs_to_craft":"600",
	  "gold_to_craft":"19",
	  "xp_from_craft":"430",
	  "crafted_in_bench":true,
	  "materials":{
		 "cloth":"1"
	  }
   },
   "leather_helmet":{
	  "secs_to_craft":"773",
	  "gold_to_craft":"170",
	  "xp_from_craft":"2100",
	  "crafted_in_bench":true,
	  "materials":{
		 "leather":"3"
	  }
   },
   "leather_chestplate":{
	  "secs_to_craft":"827",
	  "gold_to_craft":"255",
	  "xp_from_craft":"2889",
	  "crafted_in_bench":true,
	  "materials":{
		 "leather":"4"
	  }
   },
   "leather_gloves":{
	  "secs_to_craft":"720",
	  "gold_to_craft":"105",
	  "xp_from_craft":"1400",
	  "crafted_in_bench":true,
	  "materials":{
		 "leather":"2"
	  }
   },
   "leather_boots":{
	  "secs_to_craft":"667",
	  "gold_to_craft":"53",
	  "xp_from_craft":"777",
	  "crafted_in_bench":true,
	  "materials":{
		 "leather":"1"
	  }
   },
   "hardleather_helmet":{
	  "secs_to_craft":"961",
	  "gold_to_craft":"351",
	  "xp_from_craft":"2646",
	  "crafted_in_bench":true,
	  "materials":{
		 "hardleather":"3"
	  }
   },
   "hardleather_chestplate":{
	  "secs_to_craft":"1016",
	  "gold_to_craft":"502",
	  "xp_from_craft":"3604",
	  "crafted_in_bench":true,
	  "materials":{
		 "hardleather":"4"
	  }
   },
   "hardleather_gloves":{
	  "secs_to_craft":"905",
	  "gold_to_craft":"225",
	  "xp_from_craft":"1780",
	  "crafted_in_bench":true,
	  "materials":{
		 "hardleather":"2"
	  }
   },
   "hardleather_boots":{
	  "secs_to_craft":"850",
	  "gold_to_craft":"119",
	  "xp_from_craft":"1004",
	  "crafted_in_bench":true,
	  "materials":{
		 "hardleather":"1"
	  }
   },
   "dulite_helmet":{
	  "secs_to_craft":"1156",
	  "gold_to_craft":"600",
	  "xp_from_craft":"3308",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"3"
	  }
   },
   "dulite_chestplate":{
	  "secs_to_craft":"1213",
	  "gold_to_craft":"847",
	  "xp_from_craft":"4455",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"4"
	  }
   },
   "dulite_gloves":{
	  "secs_to_craft":"1099",
	  "gold_to_craft":"391",
	  "xp_from_craft":"2245",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"2"
	  }
   },
   "dulite_boots":{
	  "secs_to_craft":"1042",
	  "gold_to_craft":"214",
	  "xp_from_craft":"1275",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"1"
	  }
   },
   "midite_helmet":{
	  "secs_to_craft":"1356",
	  "gold_to_craft":"925",
	  "xp_from_craft":"4022",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"3"
	  }
   },
   "midite_chestplate":{
	  "secs_to_craft":"1415",
	  "gold_to_craft":"1286",
	  "xp_from_craft":"5400",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"4"
	  }
   },
   "midite_gloves":{
	  "secs_to_craft":"1298",
	  "gold_to_craft":"612",
	  "xp_from_craft":"2750",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"2"
	  }
   },
   "midite_boots":{
	  "secs_to_craft":"1239",
	  "gold_to_craft":"340",
	  "xp_from_craft":"1575",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"1"
	  }
   },
   "shinite_helmet":{
	  "secs_to_craft":"1562",
	  "gold_to_craft":"1346",
	  "xp_from_craft":"4410",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"3"
	  }
   },
   "shinite_chestplate":{
	  "secs_to_craft":"1622",
	  "gold_to_craft":"1841",
	  "xp_from_craft":"5886",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"4"
	  }
   },
   "shinite_gloves":{
	  "secs_to_craft":"1502",
	  "gold_to_craft":"888",
	  "xp_from_craft":"3025",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"2"
	  }
   },
   "shinite_boots":{
	  "secs_to_craft":"1443",
	  "gold_to_craft":"502",
	  "xp_from_craft":"1743",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"1"
	  }
   },
   "desite_helmet":{
	  "secs_to_craft":"1771",
	  "gold_to_craft":"1823",
	  "xp_from_craft":"4578",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3"
	  }
   },
   "desite_chestplate":{
	  "secs_to_craft":"1832",
	  "gold_to_craft":"2497",
	  "xp_from_craft":"6088",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"4"
	  }
   },
   "desite_gloves":{
	  "secs_to_craft":"1711",
	  "gold_to_craft":"1248",
	  "xp_from_craft":"3155",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"2"
	  }
   },
   "desite_boots":{
	  "secs_to_craft":"1650",
	  "gold_to_craft":"704",
	  "xp_from_craft":"1826",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"1"
	  }
   },
   "lavite_helmet":{
	  "secs_to_craft":"1983",
	  "gold_to_craft":"2389",
	  "xp_from_craft":"5134",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3"
	  }
   },
   "lavite_chestplate":{
	  "secs_to_craft":"2045",
	  "gold_to_craft":"3279",
	  "xp_from_craft":"6804",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"4"
	  }
   },
   "lavite_gloves":{
	  "secs_to_craft":"1922",
	  "gold_to_craft":"1636",
	  "xp_from_craft":"3550",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"2"
	  }
   },
   "lavite_boots":{
	  "secs_to_craft":"1861",
	  "gold_to_craft":"942",
	  "xp_from_craft":"2062",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"1"
	  }
   },
   "bonite_helmet":{
	  "secs_to_craft":"2198",
	  "gold_to_craft":"3110",
	  "xp_from_craft":"5250",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"3"
	  }
   },
   "bonite_chestplate":{
	  "secs_to_craft":"2260",
	  "gold_to_craft":"4173",
	  "xp_from_craft":"6939",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"4"
	  }
   },
   "bonite_gloves":{
	  "secs_to_craft":"2136",
	  "gold_to_craft":"2129",
	  "xp_from_craft":"3640",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"2"
	  }
   },
   "bonite_boots":{
	  "secs_to_craft":"2074",
	  "gold_to_craft":"1196",
	  "xp_from_craft":"2120",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"1"
	  }
   },
   "stone_sword":{
	  "secs_to_craft":"617",
	  "gold_to_craft":"26",
	  "xp_from_craft":"590",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2"
	  }
   },
   "the_ripper":{
	  "secs_to_craft":"754",
	  "gold_to_craft":"165",
	  "xp_from_craft":"2184",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"1"
	  }
   },
   "bloodstone_sword":{
	  "secs_to_craft":"693",
	  "gold_to_craft":"73",
	  "xp_from_craft":"1076",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2"
	  }
   },
   "deaths_echo":{
	  "secs_to_craft":"906",
	  "gold_to_craft":"399",
	  "xp_from_craft":"4224",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2",
		 "blood_essence":"1"
	  }
   },
   "soulstone_sword":{
	  "secs_to_craft":"877",
	  "gold_to_craft":"163",
	  "xp_from_craft":"1380",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2"
	  }
   },
   "frostweaver":{
	  "secs_to_craft":"1099",
	  "gold_to_craft":"756",
	  "xp_from_craft":"5208",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2",
		 "ectoplasm":"1"
	  }
   },
   "dulite_sword":{
	  "secs_to_craft":"1070",
	  "gold_to_craft":"293",
	  "xp_from_craft":"1746",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"2"
	  }
   },
   "ol_stumpy":{
	  "secs_to_craft":"1299",
	  "gold_to_craft":"1241",
	  "xp_from_craft":"6360",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"1"
	  }
   },
   "midite_sword":{
	  "secs_to_craft":"1269",
	  "gold_to_craft":"467",
	  "xp_from_craft":"2150",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"2"
	  }
   },
   "roboblade":{
	  "secs_to_craft":"1503",
	  "gold_to_craft":"1890",
	  "xp_from_craft":"7656",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"1"
	  }
   },
   "shinite_sword":{
	  "secs_to_craft":"1473",
	  "gold_to_craft":"680",
	  "xp_from_craft":"2372",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"2"
	  }
   },
   "one_inch_poker":{
	  "secs_to_craft":"1711",
	  "gold_to_craft":"2667",
	  "xp_from_craft":"8280",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"1"
	  }
   },
   "desite_sword":{
	  "secs_to_craft":"1680",
	  "gold_to_craft":"957",
	  "xp_from_craft":"2478",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"2"
	  }
   },
   "elecdesite_sword":{
	  "secs_to_craft":"1922",
	  "gold_to_craft":"3552",
	  "xp_from_craft":"8520",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"2",
		 "light_essence":"1"
	  }
   },
   "lavite_sword":{
	  "secs_to_craft":"1891",
	  "gold_to_craft":"1256",
	  "xp_from_craft":"2794",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"2"
	  }
   },
   "blazite_sword":{
	  "secs_to_craft":"2136",
	  "gold_to_craft":"4676",
	  "xp_from_craft":"9480",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"2",
		 "fire_essence":"1"
	  }
   },
   "bonite_sword":{
	  "secs_to_craft":"2105",
	  "gold_to_craft":"1633",
	  "xp_from_craft":"2868",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"2"
	  }
   },
   "guthanos":{
	  "secs_to_craft":"2353",
	  "gold_to_craft":"5810",
	  "xp_from_craft":"9624",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"1"
	  }
   },
   "twisted_sword":{
	  "secs_to_craft":"2322",
	  "gold_to_craft":"2064",
	  "xp_from_craft":"3110",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"2"
	  }
   },
   "stone_dagger":{
	  "secs_to_craft":"1",
	  "gold_to_craft":"1",
	  "xp_from_craft":"1",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"1"
	  }
   },
   "jagged_edge":{
	  "secs_to_craft":"754",
	  "gold_to_craft":"165",
	  "xp_from_craft":"2184",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"1"
	  }
   },
   "bloodstone_dagger":{
	  "secs_to_craft":"2",
	  "gold_to_craft":"2",
	  "xp_from_craft":"2",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"1"
	  }
   },
   "bloodsoaker":{
	  "secs_to_craft":"906",
	  "gold_to_craft":"399",
	  "xp_from_craft":"4224",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2",
		 "blood_essence":"1"
	  }
   },
   "soulstone_dagger":{
	  "secs_to_craft":"3",
	  "gold_to_craft":"3",
	  "xp_from_craft":"3",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"1"
	  }
   },
   "the_stake":{
	  "secs_to_craft":"1099",
	  "gold_to_craft":"756",
	  "xp_from_craft":"5208",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2",
		 "ectoplasm":"1"
	  }
   },
   "dulite_dagger":{
	  "secs_to_craft":"4",
	  "gold_to_craft":"4",
	  "xp_from_craft":"4",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"1"
	  }
   },
   "dulite_kris":{
	  "secs_to_craft":"4",
	  "gold_to_craft":"4",
	  "xp_from_craft":"4",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"1"
	  }
   },
   "midite_dagger":{
	  "secs_to_craft":"5",
	  "gold_to_craft":"5",
	  "xp_from_craft":"5",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"1"
	  }
   },
   "the_blinder":{
	  "secs_to_craft":"1503",
	  "gold_to_craft":"1890",
	  "xp_from_craft":"7656",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"1"
	  }
   },
   "shinite_dagger":{
	  "secs_to_craft":"6",
	  "gold_to_craft":"6",
	  "xp_from_craft":"6",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"1"
	  }
   },
   "solid_sabre":{
	  "secs_to_craft":"1711",
	  "gold_to_craft":"2667",
	  "xp_from_craft":"8280",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"1"
	  }
   },
   "desite_dagger":{
	  "secs_to_craft":"7",
	  "gold_to_craft":"7",
	  "xp_from_craft":"7",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"1"
	  }
   },
   "elecdesite_dagger":{
	  "secs_to_craft":"1922",
	  "gold_to_craft":"3552",
	  "xp_from_craft":"8520",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"2",
		 "light_essence":"1"
	  }
   },
   "lavite_dagger":{
	  "secs_to_craft":"8",
	  "gold_to_craft":"8",
	  "xp_from_craft":"8",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"1"
	  }
   },
   "blazite_dagger":{
	  "secs_to_craft":"2136",
	  "gold_to_craft":"4676",
	  "xp_from_craft":"9480",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"2",
		 "fire_essence":"1"
	  }
   },
   "bonite_dagger":{
	  "secs_to_craft":"9",
	  "gold_to_craft":"9",
	  "xp_from_craft":"9",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"1"
	  }
   },
   "molten_pain":{
	  "secs_to_craft":"2353",
	  "gold_to_craft":"5810",
	  "xp_from_craft":"9624",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"1"
	  }
   },
   "twisted_dagger":{
	  "secs_to_craft":"10",
	  "gold_to_craft":"10",
	  "xp_from_craft":"10",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"1"
	  }
   },
   "stone_gauntlet":{
	  "secs_to_craft":"651",
	  "gold_to_craft":"49",
	  "xp_from_craft":"936",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "needlers":{
	  "secs_to_craft":"771",
	  "gold_to_craft":"203",
	  "xp_from_craft":"2412",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2"
	  }
   },
   "bloodstone_gauntlet":{
	  "secs_to_craft":"747",
	  "gold_to_craft":"130",
	  "xp_from_craft":"1740",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "singed_talons":{
	  "secs_to_craft":"933",
	  "gold_to_craft":"471",
	  "xp_from_craft":"4709",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3",
		 "blood_essence":"2"
	  }
   },
   "soulstone_gauntlet":{
	  "secs_to_craft":"933",
	  "gold_to_craft":"276",
	  "xp_from_craft":"2202",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "twin_fangs":{
	  "secs_to_craft":"1127",
	  "gold_to_craft":"880",
	  "xp_from_craft":"5778",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3",
		 "ectoplasm":"2"
	  }
   },
   "dulite_gauntlet":{
	  "secs_to_craft":"1127",
	  "gold_to_craft":"482",
	  "xp_from_craft":"2760",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"3"
	  }
   },
   "flesh_openers":{
	  "secs_to_craft":"1327",
	  "gold_to_craft":"1436",
	  "xp_from_craft":"7052",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"2"
	  }
   },
   "midite_gauntlet":{
	  "secs_to_craft":"1327",
	  "gold_to_craft":"757",
	  "xp_from_craft":"3378",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"3"
	  }
   },
   "nibblers":{
	  "secs_to_craft":"1532",
	  "gold_to_craft":"2145",
	  "xp_from_craft":"8440",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"2"
	  }
   },
   "shinite_gauntlet":{
	  "secs_to_craft":"1532",
	  "gold_to_craft":"1104",
	  "xp_from_craft":"3702",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"3"
	  }
   },
   "slice_of_life":{
	  "secs_to_craft":"1741",
	  "gold_to_craft":"2960",
	  "xp_from_craft":"9123",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"2"
	  }
   },
   "desite_gauntlet":{
	  "secs_to_craft":"1741",
	  "gold_to_craft":"1498",
	  "xp_from_craft":"3852",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3"
	  }
   },
   "elecdesite_gauntlet":{
	  "secs_to_craft":"1952",
	  "gold_to_craft":"4017",
	  "xp_from_craft":"9373",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3",
		 "light_essence":"2"
	  }
   },
   "lavite_gauntlet":{
	  "secs_to_craft":"1953",
	  "gold_to_craft":"2008",
	  "xp_from_craft":"4332",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3"
	  }
   },
   "blazite_gauntlet":{
	  "secs_to_craft":"2167",
	  "gold_to_craft":"5159",
	  "xp_from_craft":"10420",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3",
		 "fire_essence":"2"
	  }
   },
   "bonite_gauntlet":{
	  "secs_to_craft":"2167",
	  "gold_to_craft":"2555",
	  "xp_from_craft":"4434",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"3"
	  }
   },
   "pincers":{
	  "secs_to_craft":"2384",
	  "gold_to_craft":"6575",
	  "xp_from_craft":"10579",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"2"
	  }
   },
   "twisted_gauntlet":{
	  "secs_to_craft":"2384",
	  "gold_to_craft":"3232",
	  "xp_from_craft":"4794",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"3"
	  }
   },
   "stone_axe":{
	  "secs_to_craft":"720",
	  "gold_to_craft":"118",
	  "xp_from_craft":"1720",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4"
	  }
   },
   "the_hoe":{
	  "secs_to_craft":"805",
	  "gold_to_craft":"268",
	  "xp_from_craft":"2925",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "bloodstone_axe":{
	  "secs_to_craft":"853",
	  "gold_to_craft":"291",
	  "xp_from_craft":"3320",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4"
	  }
   },
   "crazed_chopper":{
	  "secs_to_craft":"986",
	  "gold_to_craft":"612",
	  "xp_from_craft":"5760",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4",
		 "blood_essence":"3"
	  }
   },
   "soulstone_axe":{
	  "secs_to_craft":"1044",
	  "gold_to_craft":"572",
	  "xp_from_craft":"4120",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4"
	  }
   },
   "double_fury":{
	  "secs_to_craft":"1182",
	  "gold_to_craft":"1119",
	  "xp_from_craft":"6975",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4",
		 "ectoplasm":"3"
	  }
   },
   "dulite_axe":{
	  "secs_to_craft":"1242",
	  "gold_to_craft":"954",
	  "xp_from_craft":"5080",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"4"
	  }
   },
   "stormedge":{
	  "secs_to_craft":"1384",
	  "gold_to_craft":"1797",
	  "xp_from_craft":"8505",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"3"
	  }
   },
   "midite_axe":{
	  "secs_to_craft":"1444",
	  "gold_to_craft":"1453",
	  "xp_from_craft":"6120",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"4"
	  }
   },
   "soul_reaper":{
	  "secs_to_craft":"1591",
	  "gold_to_craft":"2639",
	  "xp_from_craft":"10125",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"3"
	  }
   },
   "shinite_axe":{
	  "secs_to_craft":"1651",
	  "gold_to_craft":"2085",
	  "xp_from_craft":"6660",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"4"
	  }
   },
   "gutrender":{
	  "secs_to_craft":"1800",
	  "gold_to_craft":"3642",
	  "xp_from_craft":"10890",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"3"
	  }
   },
   "desite_axe":{
	  "secs_to_craft":"1862",
	  "gold_to_craft":"2835",
	  "xp_from_craft":"6880",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"4"
	  }
   },
   "elecdesite_axe":{
	  "secs_to_craft":"2013",
	  "gold_to_craft":"4841",
	  "xp_from_craft":"11160",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"4",
		 "light_essence":"3"
	  }
   },
   "lavite_axe":{
	  "secs_to_craft":"2075",
	  "gold_to_craft":"3643",
	  "xp_from_craft":"7680",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"4"
	  }
   },
   "blazite_axe":{
	  "secs_to_craft":"2228",
	  "gold_to_craft":"6216",
	  "xp_from_craft":"12375",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"4",
		 "fire_essence":"3"
	  }
   },
   "bonite_axe":{
	  "secs_to_craft":"2291",
	  "gold_to_craft":"4637",
	  "xp_from_craft":"7820",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"4"
	  }
   },
   "painbringer":{
	  "secs_to_craft":"2446",
	  "gold_to_craft":"7929",
	  "xp_from_craft":"12510",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"3"
	  }
   },
   "twisted_axe":{
	  "secs_to_craft":"2510",
	  "gold_to_craft":"5880",
	  "xp_from_craft":"8420",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"4"
	  }
   },
   "stone_spear":{
	  "secs_to_craft":"685",
	  "gold_to_craft":"79",
	  "xp_from_craft":"1320",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "bloodstone_spear":{
	  "secs_to_craft":"800",
	  "gold_to_craft":"202",
	  "xp_from_craft":"2484",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "justice":{
	  "secs_to_craft":"960",
	  "gold_to_craft":"525",
	  "xp_from_craft":"5250",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3",
		 "blood_essence":"2"
	  }
   },
   "soulstone_spear":{
	  "secs_to_craft":"988",
	  "gold_to_craft":"415",
	  "xp_from_craft":"3108",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "witherbrand":{
	  "secs_to_craft":"1155",
	  "gold_to_craft":"973",
	  "xp_from_craft":"6384",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3",
		 "ectoplasm":"2"
	  }
   },
   "dulite_spear":{
	  "secs_to_craft":"1184",
	  "gold_to_craft":"705",
	  "xp_from_craft":"3864",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"3"
	  }
   },
   "midite_spear":{
	  "secs_to_craft":"1386",
	  "gold_to_craft":"1091",
	  "xp_from_craft":"4704",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"3"
	  }
   },
   "gloompike":{
	  "secs_to_craft":"1561",
	  "gold_to_craft":"2352",
	  "xp_from_craft":"9282",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"2"
	  }
   },
   "shinite_spear":{
	  "secs_to_craft":"1592",
	  "gold_to_craft":"1566",
	  "xp_from_craft":"5136",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"3"
	  }
   },
   "truthseeker":{
	  "secs_to_craft":"1770",
	  "gold_to_craft":"3252",
	  "xp_from_craft":"9996",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"2"
	  }
   },
   "desite_spear":{
	  "secs_to_craft":"1801",
	  "gold_to_craft":"2127",
	  "xp_from_craft":"5316",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3"
	  }
   },
   "elecdesite_spear":{
	  "secs_to_craft":"1983",
	  "gold_to_craft":"4326",
	  "xp_from_craft":"10248",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3",
		 "light_essence":"2"
	  }
   },
   "lavite_spear":{
	  "secs_to_craft":"2014",
	  "gold_to_craft":"2793",
	  "xp_from_craft":"5952",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3"
	  }
   },
   "blazite_spear":{
	  "secs_to_craft":"2198",
	  "gold_to_craft":"5699",
	  "xp_from_craft":"11382",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3",
		 "fire_essence":"2"
	  }
   },
   "bonite_spear":{
	  "secs_to_craft":"2229",
	  "gold_to_craft":"3554",
	  "xp_from_craft":"6084",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"3"
	  }
   },
   "apocalypse":{
	  "secs_to_craft":"2415",
	  "gold_to_craft":"7081",
	  "xp_from_craft":"11550",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"2"
	  }
   },
   "twisted_spear":{
	  "secs_to_craft":"2447",
	  "gold_to_craft":"4501",
	  "xp_from_craft":"6564",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"3"
	  }
   },
   "stone_maul":{
	  "secs_to_craft":"737",
	  "gold_to_craft":"149",
	  "xp_from_craft":"1936",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4"
	  }
   },
   "giant_smasher":{
	  "secs_to_craft":"805",
	  "gold_to_craft":"268",
	  "xp_from_craft":"2925",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "bloodstone_maul":{
	  "secs_to_craft":"880",
	  "gold_to_craft":"354",
	  "xp_from_craft":"3762",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4"
	  }
   },
   "voice_of_reason":{
	  "secs_to_craft":"986",
	  "gold_to_craft":"612",
	  "xp_from_craft":"5760",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4",
		 "blood_essence":"3"
	  }
   },
   "soulstone_maul":{
	  "secs_to_craft":"1071",
	  "gold_to_craft":"676",
	  "xp_from_craft":"4642",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4"
	  }
   },
   "mangled_mess":{
	  "secs_to_craft":"1182",
	  "gold_to_craft":"1119",
	  "xp_from_craft":"6975",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"4",
		 "ectoplasm":"3"
	  }
   },
   "dulite_maul":{
	  "secs_to_craft":"1270",
	  "gold_to_craft":"1121",
	  "xp_from_craft":"5698",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"4"
	  }
   },
   "hatred":{
	  "secs_to_craft":"1384",
	  "gold_to_craft":"1797",
	  "xp_from_craft":"8505",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"3"
	  }
   },
   "midite_maul":{
	  "secs_to_craft":"1474",
	  "gold_to_craft":"1674",
	  "xp_from_craft":"6886",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"4"
	  }
   },
   "mourning_star":{
	  "secs_to_craft":"1591",
	  "gold_to_craft":"2639",
	  "xp_from_craft":"10125",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"3"
	  }
   },
   "shinite_maul":{
	  "secs_to_craft":"1681",
	  "gold_to_craft":"2397",
	  "xp_from_craft":"7458",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"4"
	  }
   },
   "lightbane":{
	  "secs_to_craft":"1800",
	  "gold_to_craft":"3642",
	  "xp_from_craft":"10890",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"3"
	  }
   },
   "desite_maul":{
	  "secs_to_craft":"1892",
	  "gold_to_craft":"3185",
	  "xp_from_craft":"7678",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"4"
	  }
   },
   "elecdesite_maul":{
	  "secs_to_craft":"2013",
	  "gold_to_craft":"4841",
	  "xp_from_craft":"11160",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"4",
		 "light_essence":"3"
	  }
   },
   "lavite_maul":{
	  "secs_to_craft":"2106",
	  "gold_to_craft":"4182",
	  "xp_from_craft":"8558",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"4"
	  }
   },
   "blazite_maul":{
	  "secs_to_craft":"2228",
	  "gold_to_craft":"6216",
	  "xp_from_craft":"12375",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"4",
		 "fire_essence":"3"
	  }
   },
   "bonite_maul":{
	  "secs_to_craft":"2322",
	  "gold_to_craft":"5326",
	  "xp_from_craft":"8712",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"4"
	  }
   },
   "sweet_glory":{
	  "secs_to_craft":"2446",
	  "gold_to_craft":"7929",
	  "xp_from_craft":"12510",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"3"
	  }
   },
   "twisted_maul":{
	  "secs_to_craft":"2541",
	  "gold_to_craft":"6565",
	  "xp_from_craft":"9372",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"4"
	  }
   },
   "stone_knuckles":{
	  "secs_to_craft":"651",
	  "gold_to_craft":"49",
	  "xp_from_craft":"936",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "faceplant":{
	  "secs_to_craft":"771",
	  "gold_to_craft":"203",
	  "xp_from_craft":"2412",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"2"
	  }
   },
   "bloodstone_knuckles":{
	  "secs_to_craft":"747",
	  "gold_to_craft":"130",
	  "xp_from_craft":"1740",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "subtle_sting":{
	  "secs_to_craft":"933",
	  "gold_to_craft":"471",
	  "xp_from_craft":"4709",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3",
		 "blood_essence":"2"
	  }
   },
   "soulstone_knuckles":{
	  "secs_to_craft":"933",
	  "gold_to_craft":"276",
	  "xp_from_craft":"2202",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3"
	  }
   },
   "the_pounders":{
	  "secs_to_craft":"1127",
	  "gold_to_craft":"880",
	  "xp_from_craft":"5778",
	  "crafted_in_bench":true,
	  "materials":{
		 "stone":"3",
		 "ectoplasm":"2"
	  }
   },
   "dulite_knuckles":{
	  "secs_to_craft":"1127",
	  "gold_to_craft":"482",
	  "xp_from_craft":"2760",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"3"
	  }
   },
   "winters_bite":{
	  "secs_to_craft":"1327",
	  "gold_to_craft":"1436",
	  "xp_from_craft":"7052",
	  "crafted_in_bench":true,
	  "materials":{
		 "dulite":"2"
	  }
   },
   "midite_knuckles":{
	  "secs_to_craft":"1327",
	  "gold_to_craft":"757",
	  "xp_from_craft":"3378",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"3"
	  }
   },
   "dualism":{
	  "secs_to_craft":"1532",
	  "gold_to_craft":"2145",
	  "xp_from_craft":"8440",
	  "crafted_in_bench":true,
	  "materials":{
		 "midite":"2"
	  }
   },
   "shinite_knuckles":{
	  "secs_to_craft":"1532",
	  "gold_to_craft":"1104",
	  "xp_from_craft":"3702",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"3"
	  }
   },
   "dual_knuckles":{
	  "secs_to_craft":"1741",
	  "gold_to_craft":"2960",
	  "xp_from_craft":"9123",
	  "crafted_in_bench":true,
	  "materials":{
		 "shinite":"2"
	  }
   },
   "desite_knuckles":{
	  "secs_to_craft":"1741",
	  "gold_to_craft":"1498",
	  "xp_from_craft":"3852",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3"
	  }
   },
   "elecdesite_knuckles":{
	  "secs_to_craft":"1952",
	  "gold_to_craft":"4017",
	  "xp_from_craft":"9373",
	  "crafted_in_bench":true,
	  "materials":{
		 "desite":"3",
		 "light_essence":"2"
	  }
   },
   "lavite_knuckles":{
	  "secs_to_craft":"1953",
	  "gold_to_craft":"2008",
	  "xp_from_craft":"4332",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3"
	  }
   },
   "blazite_knuckles":{
	  "secs_to_craft":"2167",
	  "gold_to_craft":"5159",
	  "xp_from_craft":"10420",
	  "crafted_in_bench":true,
	  "materials":{
		 "lavite":"3",
		 "fire_essence":"2"
	  }
   },
   "bonite_knuckles":{
	  "secs_to_craft":"2167",
	  "gold_to_craft":"2555",
	  "xp_from_craft":"4434",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"3"
	  }
   },
   "life_eater":{
	  "secs_to_craft":"2384",
	  "gold_to_craft":"6575",
	  "xp_from_craft":"10579",
	  "crafted_in_bench":true,
	  "materials":{
		 "bonite":"2"
	  }
   },
   "twisted_knuckles":{
	  "secs_to_craft":"2384",
	  "gold_to_craft":"3232",
	  "xp_from_craft":"4794",
	  "crafted_in_bench":true,
	  "materials":{
		 "twisted":"3"
	  }
   }
}
