extends Node

#Have defaults and then if a save file exists, just update the values below
var vendors = {
	0: {
		'id': 'steward',
		'name': 'Steward',
		'icon_img': 'icon_steward',
		'avatar_img': 'avatar_steward',
		'locked': false,
		'renown_needed': 0,
	},
	1: {
		'id': 'merchant',
		'name': 'Merchant',
		'icon_img': 'icon_merchant',
		'avatar_img': 'avatar_merchant',
		'locked': false,
		'renown_needed': 0,
	},
	2: {
		'id': 'messenger',
		'name': 'Messenger',
		'icon_img': 'icon_messenger',
		'avatar_img': 'avatar_messenger',
		'locked': false,
		'renown_needed': 0,
	},
	3: {
		'id': 'banker',
		'name': 'Banker',
		'icon_img': 'icon_banker',
		'avatar_img': 'avatar_banker',
		'locked': false,
		'renown_needed': 0,
	},
	4: {
		'id': 'enchanter',
		'name': 'Enchanter',
		'icon_img': 'icon_enchanter',
		'avatar_img': 'avatar_enchanter',
		'locked': false,
		'renown_needed': 0,
	},
	5: {
		'id': 'jeweler',
		'name': 'Jeweler',
		'icon_img': 'icon_jeweler',
		'avatar_img': 'avatar_jeweler',
		'locked': false,
		'renown_needed': 0,
	},
	6: {
		'id': 'carpenter',
		'name': 'Carpenter',
		'icon_img': 'icon_carpenter',
		'avatar_img': 'avatar_carpenter',
		'locked': true,
		'renown_needed': 500,
	},
	7: {
		'id': 'alchemist',
		'name': 'Alchemist',
		'icon_img': 'icon_alchemist',
		'avatar_img': 'avatar_alchemist',
		'locked': true,
		'renown_needed': 1000,
	},
	8: {
		'id': 'captain',
		'name': 'Captain',
		'icon_img': 'icon_captain',
		'avatar_img': 'avatar_captain',
		'locked': true,
		'renown_needed': 1500,
	},
	9: {
		'id': 'blacksmith',
		'name': 'Blacksmith',
		'icon_img': 'icon_blacksmith',
		'avatar_img': 'avatar_blacksmith',
		'locked': true,
		'renown_needed': 2500,
	},
}
